name: Build and Deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]

# TODO: Remove github pages deployment to only use cloudflare pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      # github pages
      - name: Build for GitHub Pages
        run: npm run build
        env:
          DEPLOY_TARGET: 'gh-pages'

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Finalize GitHub Deploy
        uses: actions/deploy-pages@v4

      # cloudflare pages
      - name: Build for Cloudflare
        run: npm run build
        env:
          DEPLOY_TARGET: 'cloudflare'

      - name: Deploy to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'portfolio'
          directory: 'dist'